### ISSUE TITLE
Selecting 'Black Night' as your character causes the client to crash

### ISSUE THREAD

**Issue by filiptodoric** [filip3311/filipdylanryan#3]
Steps to reproduce: 
1. Start the server
2. Start a client, select a character (other than the Black Knight) and select a  location 
3. Start another client, select Black Knight as your character 

Actual Result: The client crashes and the following error is thrown:
-- In buildCharInternalFrame().
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
    at View.MagicRealmGUI.getStartLocation(MagicRealmGUI.java:474)
    at Networking.MagicRealmClient.run(MagicRealmClient.java:432)
    at Networking.MagicRealmClient.main(MagicRealmClient.java:490)

Expected Result: A dialog box should display and ask the user where they want the Black Knight to start at.

This occurred in the most recent build of Magic Realm.

**Comment by gr81ape** [comment]
Peer-tested, bug's fixed! Thanks for the patch Fil.
